source 'https://rubygems.org'

ruby '3.0.0'

gem 'sinatra', '~> 3.0'
gem 'sinatra-contrib', '~> 3.0'
gem 'rack-cors', '~> 2.0'
gem 'json', '~> 2.6'
gem 'dotenv', '~> 2.8'
gem 'pg', '~> 1.4'
gem 'activerecord', '~> 7.0'
gem 'sinatra-activerecord', '~> 2.0'
gem 'jwt', '~> 2.7'
gem 'mail', '~> 2.8'
gem 'twilio-ruby', '~> 6.0'
gem 'redis', '~> 5.0'
gem 'puma', '~> 6.0'
gem 'rake', '~> 13.0'
gem 'sinatra-swagger-exposer', '~> 0.8.0'

group :development, :test do
  gem 'rspec', '~> 3.12'
  gem 'rack-test', '~> 2.1'
  gem 'factory_bot', '~> 6.2'
end
