
server.port=8088

spring.datasource.url=rolesdb.cciv7q9nagis.us-east-1.rds.amazonaws.com
spring.datasource.username=postgres
spring.datasource.password=roles123


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
