package main

import (
	"fmt"
	"listSpaces/config"
	"listSpaces/routes"
	"os"

	"github.com/gin-gonic/gin"
	// Swagger imports
	_ "listSpaces/docs" // docs is generated by Swag CLI, you have to import it.

	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

func main() {
	config.InitDB()

	router := gin.Default()
	routes.SetupRoutes(router)

	router.GET("/", func(c *gin.Context) {
		c.JSON(200, gin.H{
			"message": "listService is running",
		})
	})
	router.GET("/listSpaces", func(c *gin.Context) {
		c.JSON(200, gin.H{
			"message": "listService is running",
		})

	})
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	port := os.Getenv("PORT")
	if port == "" {
		port = "3010"
	}

	router.Run(fmt.Sprintf(":%s", port))
}
