package main

import (
	"createSpace/config"
	"createSpace/routes"
	"fmt"
	"os"

	_ "createSpace/docs" // docs is generated by Swag CLI, you have to import it.

	"github.com/gin-gonic/gin"

	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

func main() {
	config.InitDB()

	router := gin.Default()
	routes.SetupRoutes(router)

	// Swagger route
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	port := os.Getenv("PORT")
	if port == "" {
		port = "3008"
	}

	router.Run(fmt.Sprintf(":%s", port))
}
