name: Deploy UserManagement Microservices

on:
  push:
    branches:
      - test
    paths:
      - 'backend/User_Management/**'
      - '.github/workflows/deploy_users.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run unit tests for UserManagement
        run: |
            # findUser
            pip install -r backend/User_Management/findUser/requirements.txt
            python -m unittest discover -s backend/User_Management/findUser/tests

            # getUserByUsername
            pip install -r backend/User_Management/getUserByUsername/requirements.txt
            python -m unittest discover -s backend/User_Management/getUserByUsername/tests

            # login_auth
            pip install -r backend/User_Management/login_auth/requirements.txt
            python -m unittest discover -s backend/User_Management/login_auth/tests

            # registerUser
            pip install -r backend/User_Management/registerUser/requirements.txt
            python -m unittest discover -s backend/User_Management/registerUser/tests

            # resetPassword
            pip install -r backend/User_Management/resetPassword/requirements.txt
            python -m unittest discover -s backend/User_Management/resetPassword/tests

            # sendRecoveryCode
            pip install -r backend/User_Management/sendRecoveryCode/requirements.txt
            python -m unittest discover -s backend/User_Management/sendRecoveryCode/tests

            # updateProfile
            pip install -r backend/User_Management/updateProfile/requirements.txt
            python -m unittest discover -s backend/User_Management/updateProfile/tests

            # userProfile
            pip install -r backend/User_Management/userProfile/requirements.txt
            python -m unittest discover -s backend/User_Management/userProfile/tests

      - name: Detect changed microservices
        id: changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            login_auth: backend/User_Management/login_auth/**
            registerUser: backend/User_Management/registerUser/**
            resetPassword: backend/User_Management/resetPassword/**
            sendRecoveryCode: backend/User_Management/sendRecoveryCode/**
            updateProfile: backend/User_Management/updateProfile/**
            userProfile: backend/User_Management/userProfile/**
            findUser: backend/User_Management/findUser/**
            getUserByUsername: backend/User_Management/getUserByUsername/**

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push UserManagement images
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/login-auth:v1 ./backend/User_Management/login_auth
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/login-auth:v1

          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/register-user:v1 ./backend/User_Management/registerUser
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/register-user:v1

          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/reset-password:v1 ./backend/User_Management/resetPassword
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/reset-password:v1

          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/send-recovery-code:v1 ./backend/User_Management/sendRecoveryCode
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/send-recovery-code:v1

          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/update-profile:v1 ./backend/User_Management/updateProfile
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/update-profile:v1

          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/user-profile:v1 ./backend/User_Management/userProfile
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/user-profile:v1

          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/find-user:v1 ./backend/User_Management/findUser
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/find-user:v1

          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/get-user-by-username:v1 ./backend/User_Management/getUserByUsername
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/get-user-by-username:v1



      - name: Deploy to EC2
        if: success()
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS_USERS }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY_USERS }}
          port: 22
          script: |
            sudo apt update && sudo apt install -y docker.io || true
            sudo systemctl start docker

            echo "..."
            docker ps -aq | xargs -r docker stop
            docker ps -aq | xargs -r docker rm

            echo "🧹..."
            docker image rm -f \
              ${{ secrets.DOCKERHUB_USERNAME }}/login-auth:v1 \
              ${{ secrets.DOCKERHUB_USERNAME }}/register-user:v1 \
              ${{ secrets.DOCKERHUB_USERNAME }}/reset-password:v1 \
              ${{ secrets.DOCKERHUB_USERNAME }}/send-recovery-code:v1 \
              ${{ secrets.DOCKERHUB_USERNAME }}/update-profile:v1 \
              ${{ secrets.DOCKERHUB_USERNAME }}/user-profile:v1 \
              ${{ secrets.DOCKERHUB_USERNAME }}/find-user:v1 \
              ${{ secrets.DOCKERHUB_USERNAME }}/get-user-by-username:v1 || true


              # LOGIN AUTH
              if [[ "${{ steps.changes.outputs.login_auth }}" == 'true' ]]; then
                sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/login-auth:v1
                sudo docker stop login-auth || true
                sudo docker rm login-auth || true
                sudo docker run -d --name login-auth -p 5000:5000 \
                  --memory="300m" --cpus="0.5" \
                  -e DB_USERNAME="${{ secrets.DB_USERNAME_MYSQL }}" \
                  -e DB_PASSWORD="${{ secrets.DB_PASSWORD_MYSQL }}" \
                  -e DB_HOST="${{ secrets.DB_HOST_MYSQL }}" \
                  -e DB_NAME="${{ secrets.DB_NAME_MYSQL }}" \
                  ${{ secrets.DOCKERHUB_USERNAME }}/login-auth:v1
                sleep 2
              fi

              # REGISTER USER
              if [[ "${{ steps.changes.outputs.registerUser }}" == 'true' ]]; then
                sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/register-user:v1
                sudo docker stop register-user || true
                sudo docker rm register-user || true
                sudo docker run -d --name register-user -p 5001:5001 \
                  --memory="300m" --cpus="0.5" \
                  -e DB_USERNAME="${{ secrets.DB_USERNAME_MYSQL }}" \
                  -e DB_PASSWORD="${{ secrets.DB_PASSWORD_MYSQL }}" \
                  -e DB_HOST="${{ secrets.DB_HOST_MYSQL }}" \
                  ${{ secrets.DOCKERHUB_USERNAME }}/register-user:v1
                sleep 2
              fi

              # RESET PASSWORD
              if [[ "${{ steps.changes.outputs.resetPassword }}" == 'true' ]]; then
                sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/reset-password:v1
                sudo docker stop reset-password || true
                sudo docker rm reset-password || true
                sudo docker run -d --name reset-password -p 5006:5006 \
                  --memory="300m" --cpus="0.5" \
                  -e DB_USERNAME="${{ secrets.DB_USERNAME_MYSQL }}" \
                  -e DB_PASSWORD="${{ secrets.DB_PASSWORD_MYSQL }}" \
                  -e DB_HOST="${{ secrets.DB_HOST_MYSQL }}" \
                  -e REDIS_HOST="${{ secrets.REDIS_HOST_USER }}" \
                  -e REDIS_PORT="${{ secrets.REDIS_PORT_USER }}" \
                  ${{ secrets.DOCKERHUB_USERNAME }}/reset-password:v1
                sleep 2
              fi

              # SEND RECOVERY CODE
              if [[ "${{ steps.changes.outputs.sendRecoveryCode }}" == 'true' ]]; then
                sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/send-recovery-code:v1
                sudo docker stop send-recovery-code || true
                sudo docker rm send-recovery-code || true
                sudo docker run -d --name send-recovery-code -p 5005:5005 \
                  --memory="300m" --cpus="0.5" \
                  -e DB_USERNAME="${{ secrets.DB_USERNAME_MYSQL }}" \
                  -e DB_PASSWORD="${{ secrets.DB_PASSWORD_MYSQL }}" \
                  -e DB_HOST="${{ secrets.DB_HOST_MYSQL }}" \
                  -e REDIS_HOST="${{ secrets.REDIS_HOST_USER }}" \
                  -e REDIS_PORT="${{ secrets.REDIS_PORT_USER }}" \
                  -e GMAIL_USER="${{ secrets.GMAIL_USER }}" \
                  -e GMAIL_APP_PASSWORD="${{ secrets.GMAIL_APP_PASSWORD }}" \
                  ${{ secrets.DOCKERHUB_USERNAME }}/send-recovery-code:v1
                sleep 2
              fi

              # UPDATE PROFILE
              if [[ "${{ steps.changes.outputs.updateProfile }}" == 'true' ]]; then
                sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/update-profile:v1
                sudo docker stop update-profile || true
                sudo docker rm update-profile || true
                sudo docker run -d --name update-profile -p 5008:5008 \
                  --memory="300m" --cpus="0.5" \
                  -e DOCDB_URI="${{ secrets.DOCDB_URI_MONGO_PROFILE }}" \
                  -e DOCDB_DATABASE="${{ secrets.DOCDB_DATABASE_MONGO_PROFILE }}" \
                  ${{ secrets.DOCKERHUB_USERNAME }}/update-profile:v1
                sleep 2
              fi

              # USER PROFILE
              if [[ "${{ steps.changes.outputs.userProfile }}" == 'true' ]]; then
                sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/user-profile:v1
                sudo docker stop userprofileservice || true
                sudo docker rm userprofileservice || true
                sudo docker stop user-profile || true
                sudo docker rm user-profile || true
                sudo docker run -d --name user-profile -p 5010:5010 \
                  --memory="300m" --cpus="0.5" \
                  -e DOCDB_URI="${{ secrets.DOCDB_URI_MONGO_PROFILE }}" \
                  -e DOCDB_DATABASE="${{ secrets.DOCDB_DATABASE_MONGO_PROFILE }}" \
                  ${{ secrets.DOCKERHUB_USERNAME }}/user-profile:v1
                sleep 2
              fi

              # FIND USER
              if [[ "${{ steps.changes.outputs.findUser }}" == 'true' ]]; then
                echo "Deploying find-user..."
                sudo docker stop find-user || true
                sudo docker rm find-user || true
                sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/find-user:v1
                sudo docker run -d --name find-user -p 5002:5002 \
                  --memory="300m" --cpus="0.5" \
                  -e DB_USERNAME="${{ secrets.DB_USERNAME_MYSQL }}" \
                  -e DB_PASSWORD="${{ secrets.DB_PASSWORD_MYSQL }}" \
                  -e DB_HOST="${{ secrets.DB_HOST_MYSQL }}" \
                  ${{ secrets.DOCKERHUB_USERNAME }}/find-user:v1
                sleep 2
              fi

              # GET PROFILE BY USERNAME
              if [[ "${{ steps.changes.outputs.getUserByUsername }}" == 'true' ]]; then
                sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/get-user-by-username:v1
                sudo docker stop get-profile-user || true
                sudo docker rm get-profile-user || true
                sudo docker stop get-user-by-username || true
                sudo docker rm get-user-by-username || true
                sudo docker run -d --name get-user-by-username -p 5007:5007 \
                  --memory="300m" --cpus="0.5" \
                  -e DOCDB_URI="${{ secrets.DOCDB_URI_MONGO_PROFILE }}" \
                  -e DOCDB_DATABASE="${{ secrets.DOCDB_DATABASE_MONGO_PROFILE }}" \
                  ${{ secrets.DOCKERHUB_USERNAME }}/get-user-by-username:v1
                sleep 2
              fi